---
title: "Exploring the evidence for use of cefiderocol as part of combination therapies: a systematic review of *in vitro*, *in vivo*, and clinical studies"

author:
  - name: Marco Meroi
    equal-contributor: true
    affiliation:
      - ref: verona

  - name: Juan Antonio del Castillo Polo
    equal-contributor: true
    affiliation:
      - ref: spain

  - name: Rebecca Scardellato
    affiliation:
      - ref: verona

  - name: Alessandra Nazeri
    affiliation:
      - ref: verona

  - name: Alessia Savoldi
    affiliation:
      - ref: verona

  - name: Renata Da Costa
    affiliation:
      - ref: gardp

  - name: Laura Piddock
    affiliation:
      - ref: gardp

  - name: Jennifer Cohn
    affiliation:
      - ref: gardp

  - name: Evelina Tacconelli
    affiliation:
      - ref: verona

  - name: Matteo Morra
    corresponding: true
    email: matteo.morra@univr.it
    affiliation:
      - ref: verona

  - name: Elda Righi
    affiliation:
      - ref: verona

affiliations:
  - id: verona
    name: "Division of Infectious Diseases, Department of Diagnostics and Public Health, University of Verona, Verona, Italy"

  - id: spain
    name: "Servicio de Microbiología, Hospital Universitario Ramón y Cajal and Instituto Ramón y Cajal de Investigación Sanitaria (IRYCIS), Madrid, Spain"

  - id: gardp
    name: "Global Antibiotic Research and Development Partnership (GARDP), Geneva, Switzerland"
    
keywords: 
  - cefiderocol
  - combination therapy
  - systematic review
  - in vitro studies
  - in vivo studies
  - human studies 
  
bibliography: bibliography.bib
csl: Utils/elsevier-vancouver.csl

lang: en

filters:
  - authors-block
    
format:
  wordcount-docx: default
  pdf:
    keep-tex: true
    # in terminal: quarto pandoc --print-default-data-file reference.docx > reference.docx
    reference-doc: Utils/custum-reference-doc.docx

# format:
#   elsevier-pdf:
#     keep-tex: true
#     journal:
#       formatting: review
#       model: 1p
#       cite-style: number
---

# **Introduction**

Cefiderocol is a novel siderophore–cephalosporin that has emerged as a promising agent against multidrug-resistant Gram-negative bacteria (MDR-GNB), including carbapenem-resistant (CR) Enterobacterales, *Pseudomonas aeruginosa*, and *Acinetobacter* species [@ito2016; @hackel2018].

While most recent guidelines for usage of cefiderocol consistently recommend monotherapy  for CRE and CRPA infections, when susceptibility is confirmed in vitro, there is no consensus on indications for CRAB infections [@paul2022; @tamma2024]. The 2024 Infectious Diseases Society of America (IDSA) guidance suggests the use of cefiderocol as an alternative agent for CRAB infections, specifically for cases refractory to other treatments or when patients cannot tolerate other options, always within a combination regimen, on the basis that there is insufficient evidence that supports the effectiveness of any single molecule when used alone. Conversely, the 2022  European Society of Clinical Microbiology and Infectious Diseases (ESCMID) guidelines conditionally recommend against the use of cefiderocol for CRAB infections, mainly on the basis of results of a single randomised study showing increased mortality in patients receiving cefiderocol compared to those receiving the best available treatment [@paul2022; @tamma2024].

The 2019 COHERENCE survey, involving 1012 experts worldwide, identified the intent to improve efficacy (81% of respondents) and to prevent resistance (51% of respondents) as the main reasons for the use of combination therapy in the treatment of CR-GNB infections, although many experts acknowledged the poor quality of supporting data and the lack of standardisation of regimens [@carrara2022]. Similar findings emerged from the CLEARER 2023 global survey, focusing on cefiderocol perception and prescribing attitudes, in which combination therapy was frequently preferred for CRAB and MBL-producing GNB infections, particularly to minimise resistance development and in the case of critical illness (personal data, under publication).

This systematic review aims to evaluates the efficacy of cefiderocol-based combination therapy compared with monotherapy in treatingCR-GNB infections. Evidence is synthesised across *in vitro* studies assessing synergy, *in vivo* models evaluating bacterial clearance, and clinical trials examining mortality, clinical cure, and microbiological eradication.

# Methods

## **Search strategy and eligibility criteria**

A Medline-based search was conducted from 1^st^ of January 2015 until 31^st^ of January 2025 using "cefiderocol\[tw\]" or "S-649266\[tw\]” as keywords to identify *in vivo, in vitro*, and clinical studies on humans reporting data on cefiderocol as part of combination regimens. Only studies published in the English language were included. The screening process was conducted independently by three authors (Ma.Mo., J.DC, and R.S.) and disagreements were addressed by involving a third reviewer (E.R. or Ma.Me.). If eligibility could not be determined, the full article was retrieved. References of reviews and original publications were hand searched for further eligible studies.For *in vitro* studies, an additional web-based search of abstracts presented at the annual European Congress of Clinical Microbiology and Infectious Diseases (ECCMID) and IDWeek was conducted by systematically screening the ESCMID eLibrary and the Open Forum Infectious Diseases library, respectively, over the same period. All *in vivo* and *in vitro* studies were included, except for case reports, irrespective of  the technique performed to evaluate synergies.

Regarding human studies, randomised trials, observational comparative studies, and non-comparative cohort studies were included, provided that they reported on cefiderocol-based combination therapy. Case reports and case series with fewer than ten patients were excluded.

## **Data extraction and synthesis**

A standardised data-extraction method was used to record relevant features from each study into a database, including year of publication, country, study design, number of isolates/animals/patients included, type of bacterium cultured, type of antibiotic molecules tested, antibiotic susceptibility profile, type of infection, and setting. The susceptibility profile of isolates to the antibiotic(s) tested, including cefiderocol, were extracted, when available, according to the microbiological guidelines for breakpoint interpretation adopted by the individual study.  Results were presented narratively, grouped by pathogen species for *in vitro* and *in vivo* studies and by study design for clinical studies.

Limited to the clinical studies, a pair-wise meta-analysis was conducted comparing clinical and microbiological outcomes in cefiderocol monotherapy vs. cefiderocol-based combination therapy. Only studies with more than 25 patients were considered for the pooled analysis; case series and non-comparative reports were excluded. Full methodology is detailed in the **Supplementary Material**.

## **Quality assessment**

Two independent reviewers (Ma.Mo. and Ma.Me.) assessed the study quality using two different tools according to the study design**:** Cochrane Risk of Bias tool for randomised trials and the Newcastle-Ottawa Scale for observational cohort studies.

# Results

A total of 1496 citations were retrieved. From these, 191 articles were included for further screening and 66 (34 *in vitro,* 2 *in vivo*, and 30 clinical studies) met the eligibility criteria and were included in the evidence assessment. Four ECCMID abstracts and three IDWeek abstracts were identified.  Three *in vivo* models were described by the authors as part of *in vitro* articles.

PRISMA flow chart for data search and extraction, screening, and selection process is displayed in **Figure 1**. Results are reported by type of studies.

## ***In vitro*** **studies**

A total of 34 studies were included, 11 of them with ≥30 isolates and 20 with cefiderocol-resistant isolates. Eighteen of them included combinations with avibactam and seven with sulbactam, whereas xeruborbactam and meropenem were the most frequent companion molecules(325 and 274, respectively). Four methods were used to assess synergism: time-kill assays (12 studies), checkerboard analysis (13), broth microdilution (nine), and gradient diffusion strip crossing (seven), with nine studies employing ≥1 method.

Overall, combinations with β-lactamase inhibitors, particularly novel agents, emerged as the most promising ones in most cases (**Table 1**). Some experiments included different bacterial species. In a study with 82 GNB, meropenem showed synergy for all species, while amikacin and colistin were not synergistic in *P. aeruginosa* [@tsuji2016]. In another evaluation, no synergy was demonstrated with piperacillin-tazobactam, meropenem-vaborbactam, or imipenem-relebactam and synergy with fosfomycin and ceftazidime-avibactam was found only in two isolates [@palombo2023], but ceftazidime-avibactam also caused a ≥8-fold MIC decrease in 32 of 33 non-NDM-producing GNB [@kohira2020]. Synergy was found for ceftazidime-avibactam, ceftolozane-tazobactam, and meropenem for non-NDM-producing isolates from SIDERO-WT-2014 study [@yamano2020]. Cefiderocol-sulbactam enhanced cefiderocol activity in six GNB [@lewis2024] and positive interaction but no synergy was observed for glycine in ten GNB [@giordano2024].  Zidebactam, another beta-lactamase inibhitor (BLI), was found synergistic in *P. aeruginosa* and in Enterobacterales, and avibactam, zidebactam, taniborbactam, and relebactam combinations increased cefiderocol susceptibility rates more than 80% in *A. baumannii* complex [@leterrier2024; @xu2025]. Xeruborbactam significantly improved cefiderocol activity in two studies with 160 and 165 139 CR GNB [@hara2025; @hara2025a].

### ***Acinetobacter baumannii*** **complex**

Synergy with amikacin was shown in 7 amikacin-resistant isolates  [@tsuji2016; @abdul-mutakabbir2020] and with tigecycline, minocycline, meropenem, and sulbactam in cefiderocol-resistant isolates [@abdul-mutakabbir2020]. Besides this, tigecycline showed synergism in 123 isolates, confirmed *in vivo* with a *Galleria mellonella* model [@ni2022], as well as other tetracycline analogues (minocycline, tigecycline, eravacycline, and omadacycline) in CRAB isolates, verifying the eravacycline synergism in a neutropenic murine thigh-infection model [@yin2025]. No synergy was observed with colistin, tigecycline, or fosfomycin in 15 CRAB*,* potentially due to the use of the gradient diffusion strip crossing technique [@stolfa2021].

Among β-lactams, cefiderocol synergism with meropenem was demonstrated in one study but was not reported in other three studies [@tsuji2016; @yamano2020; @abdul-mutakabbir2020; @ni2022]. Avibactam and sulbactam were found synergistic in two cefiderocol-resistant PER-producing isolates, but not tazobactam, avibactam, vaborbactam, or relebactam in seven OXA-carbapenemase-producing isolates [@yamano2020; @bianco2022]. Cefiderocol-zidebactam was shown as a promising combination by an *in silico* analysis [@gopikrishnan2023] and durlobactam lowered the cefiderocol-MIC~50~ and MIC~90~ of 66 isolates but sulbactam did not [@huband2023]. In another study, only the cefiderocol-sulbactam-tigecycline combination achieved synergy in an extensively drug-resistant (XDR) *A. baumannii* strain from a patient with ventilator associated pneumonia (VAP) [@kobic2022]. Of note, exposure of *A. baumannii* to cefiderocol and sulbactam or avibactam led to the selection of resistant strains [@wong2024]. Cefiderocol, polymyxin B, and rifampicin showed synergistic effects by artificial intelligence but ampicillin-sulbactam exhibited significant antagonistic interaction [@you2025]**.**

### **Enterobacterales**

Synergies with BLIs have been the most frequently evaluated, demonstrated in tazobactam, avibactam, vaborbactam, and relebactam in three OXA-48 producers but very low synergy with tazobactam, relebactam, and avibactam and no synergy with vaborbactam was found in 7 MBL producers [@bianco2022]. In addition, no synergy with avibactam was shown in 10 double-carbapenemase producers [@bianco2022a], but it was found synergistic in 20 NDM-producing *Enterobacter cloacae* isolates [@göpel2024].

In *Klebsiella pneumoniae*, synergy with avibactam was demonstrated in different experiments including KPC and NDM-producers [@bianco2022; @bianco2022a; @boattini2023; @moon2023] and it produced the most remarkable fold reduction in the MIC compared to other BLIs in 34 isolates [@daoud2023]. However, cefiderocol activity was not improved by the addition of avibactam alone but only when aztreonam or dipicolinic acid was also added in one isolate producing NDM-1, OXA-232 and CTX-M-15 and with a mutation in catecholate-siderophore receptor . Relebactam and vaborbactam were found synergic in 18 KPC-producers [@bianco2022a], and synergy with meropenem was demonstrated in one KPC-producer, but it was not confirmed for amikacin [@tsuji2016].

### ***Pseudomonas aeruginosa***

No synergy was shown for avibactam, vaborbactam, or tazobactam in one MBL-producer, but it was found for relebactam in this isolate [@bianco2022] and two VIM-producers, and for imipenem-relebactam in two IMP-producers [@boattini2023; @granata2025]. Cotreatment with imipenem resulted in synergistic bactericidal activity in five isolates [@ferretti2024]; however, no synergy for meropenem or amikacin was found in one VIM-producer [@tsuji2016]. Colistin significantly improved cefiderocol efficacy against biofilms in two isolates in an *in vitro* pharmacodynamic model [@elhaj2024]. Vancomycin addition to cefiderocol was indifferent in two isolates [@schilling2024] and colloidal bismuth citrate (CBS) showed synergism, confirmed in a murine acute pneumonia model, and increased cefiderocol efficacy against biofilm formation, restored susceptibility in a cefiderocol-resistant isolate and significantly increased survival rate and decreased the bacterial load *in vivo* [@wang2023].

### ***Stenotrophomonas maltophilia***

Different synergy values were found with levofloxacin, minocycline, polymyxin B, and trimethoprim-sulfamethoxazole among 9 isolates [@biagi2020]. 

## ***In vivo*** **studies**

Three *in vitro* studies also included an *in vivo* model [@ni2022; @yin2025; @wang2022]. Ni *et al.* demonstrated increased survival in a *Galleria mellonella* model for both cefiderocol-resistant CRAB (treated with cefiderocol and either colistin or tigecycline) and for cefiderocol-susceptible CRAB (treated with cefiderocol and tigecycline). In this study all the isolates were susceptible to colistin [@ni2022]. Wang *et al.* demonstrated increased survival for combination of cefiderocol with CBS in a *P. aeruginosa* murine pneumonia model and Yin *et al*. verified the cefiderocol-eravacycline bacterial cell reduction in a neutropenic murine thigh-infection [@yin2025; @wang2023]. Two studies were retrieved with an exclusive focus on an in vivo model [@ding2024; @gill2023]. Ding *et al*. have evaluated nanomedicine elements in a mouse intra-abdominal infection model. Deferiprone-loaded layered double hydroxide-based therapy associated with cefiderocol suppressed the emergence of drug-resistant bacteria and enhanced the bactericidal efficacy [@ding2024].

Cefiderocol efficacy and resistance were tested in combination with ceftazidime-avibactam, ampicillin-sulbactam, or meropenem against *A. baumannii* complex isolates using human-simulated regimens in a murine thigh infection model. The isolates were classified according to cefiderocol MICs (three had MIC of 2 mg/L, 2 of 8 mg/L, and ten of ≥ 32 mg/L) and some included VEB and PER β-lactamases. When cefiderocol was combined with ceftazidime-avibactam or ampicillin-sulbactam in isolates that were cefiderocol- and ceftazidime-avibactam-resistant, mean log~10~ CFU/thigh reductions of −3.75 ± 0.37 and −3.55 ± 0.50 were observed, respectively. The combination with meropenem was less effective. Post-treatment, combination with ceftazidime-avibactam and ampicillin-sulbactam did not show MICs increase; conversely, cefiderocol monotherapy was associated with elevated MICs in all three isolates with baseline MICs of 2 mg/L. *In vitro* disk stacking assessments demonstrated a return of all tested isolates treated with ceftazidime-avibactam or ampicillin-sulbactam combinations to the Clinical & Laboratory Standards Institute (CLSI) intermediate breakpoint [@gill2023].

## **Clinical studies**

Three prospective, 28 retrospective observational studies, and one randomised trial were included for the analysis. The risk of bias  was either moderate or high for cohort studies and (**Supplementary Table 3**) and moderate for the randomised trial. Cohort studies were often monocentric [@dalfino2023; @falcone2022; @mazzitelli2023; @russo2024; @bavaro2023; @piccica2023; @gavaghan2023; @frattari2024; @oliva2024], focusing exclusively [@dalfino2023; @falcone2022; @mazzitelli2023; @russo2024; @bavaro2023] or mainly [@piccica2023; @gavaghan2023; @elghali2024; @clancy2024] on CRAB infections, and some used cefiderocol as a rescue therapy [@mazzitelli2023; @bavaro2023; @giannella2023]. Only four articles, including 142, 41, 38, 200 and 45 patients respectively, compared cefiderocol monotherapy with combination therapy as a primary outcome [@piccica2023; @palermo2023; @buonomo2024; @giacobbe2024]. Over 15 antibiotic combinations were used in different studies, including the association with antibiotics without *in vitro* activity against target CR-GNB. Detailed data and results  of the single studies are summarized in **Table 2.**

In the exploratory meta-analysis comparing monotherapy with cefiderocol and combination therapy, the pooled 30-day all cause mortality was computed on 854 patients (nine studies), while pooled clinical and microbiological cure was computed on 799 patients (nine studies) and 454 patients (five studies), respectively. Pooled mortality was significantly higher among patients receiving cefiderocol combination therapy (OR = 1.42, 95% CI: 1.03–1.95). No significant differences were observed between combination therapy and monotherapy in terms of clinical cure (OR = 0.79, 95% CI: 0.48–1.31) or microbiological eradication (OR = 0.96, 95% CI: 0.57–1.63).

# **Discussion**

This study comprehensively assessed the state of art of the cefiderocol-based combination treatments against CR-GNB infections encompassing *in vitro* and *in vivo studies* as well as current clinical practice. **Figure 2** summarises the main findings and limitations of the studies included.

*In vitro* experiments with cefiderocol combinations may elucidate which combinations could be synergistic for both cefiderocol-susceptible and resistant isolates. Results from these studies can be equally useful, the former to outline the mechanisms that reduce cefiderocol MICs, and the latter to investigate how to overcome cefiderocol resistance. However, there are some limitations hampering the comparability and therefore the applicability of results into practice. First, different techniques were employed for assessing the synergy. Reduction of CFU/mL in time was assessed by time-kill assays, whereas MIC changes were evaluated using the fractional inhibitory concentration index in most experiments. MICs were obtained by broth microdilution in checkerboard analysis. Moreover, conclusions from studies using MIC gradient test strips should be interpreted carefully and might not be as valid as other techniques [@bonnin2022]. Second, several *in vitro* experiments have analysed different types of resistant bacteria in an aggregate manner, making it difficult to interpret the results as distinct resistance patterns were found. Third, the number of isolates varied widely across studies, with the majority including small experiments. Even when considering these drawbacks, the most relevant synergies identified for clinical application were BLIs, tigecycline, meropenem, ceftazidime-avibactam and, to a lesser extent, colistin, and fosfomycin. An increasing number of *in vitro* studies, involving considerable numbers of isolates, suggests that cefiderocol combined with BLIs may be active against selected pathogens. Of the BLIs evaluated, sulbactam has shown promising activity when combined with cefiderocol against CRAB. Although sulbactam–durlobactam with imipenem is currently recommended as first-line therapy by the IDSA guidance for this pathogen, the optimal companion agent, particularly for MBL producing strains, remains undefined. Based on current *in vitro* data, cefiderocol may therefore represent a good candidate to combine with sulbactam-dorlubactam. Another promising option is cefiderocol in combination with xeruborbactam, a bicyclic boronate β-lactamase inhibitor currently tested in combination with cefiderocol in a phase 1 clinical trial. The two recent in vitro studies by Hara et al, which overall tested 325 cefiderocol-resistant isolates (165 *Enterobacterales* and 160 *A. baumannii*), represent the largest datasets to date evaluating cefiderocol combinations. Both studies employed the reference broth microdilution method in iron-depleted cation-adjusted Mueller-Hinton broth, following CLSI guidelines. To date, no other combination has been tested on such a large number of cefiderocol-resistant isolates using this standardised approach [@hara2025a; @hara2025b].

Evidence from *in vivo* studies remains scarce and provides limited insights. Although some studies have assessed *in vivo* the synergistic effects observed *in vitro* using various methods, these investigations have typically involved only a small number of isolates, limiting the strength of the conclusions that can be drawn.

The number of observational studies on the use of cefiderocol has increased in recent years, reflecting the expanding clinical use of this agent and the growing interest in optimizing its clinical application. Cefiderocol used in combination, in particular with fosfomycin as companion agent, appears promising [@falcone2022; @russo2024; @russo2023], especially for the treatment of CRAB infections. Our meta-analysis suggests that cefiderocol combination therapy does not confer a consistent advantage over monotherapy, irrespective of type of pathogen considered. While pooled estimates slightly favored combination therapy for microbiological eradication, confidence intervals were wide and subgroup differences were generally not statistically significant or based on limited study numbers.

Nonetheless, a major limitation in evaluating the efficacy of cefiderocol-based combination therapy in human studies lies in the heterogeneity and methodological quality of the available data. In many cohorts, cefiderocol was combined with various companion antibiotics leading to outcome aggregation across non-uniform regimens. This may have masked potential benefits by including combinations with antagonistic or toxic effects. The lack of detailed microbiological characterisation, particularly regarding resistance mechanisms like MBLs, further limits the ability to interpret treatment effects across different bacterial profiles. Moreover, most observational studies did not adequately adjust for confounding variables. Patients receiving combination therapy were often more severely ill or have a higher risk of mortality at baseline, which may bias outcomes in favor of monotherapy. As a result, the apparent lack of benefit observed in some studies may reflect confounding by indication rather than a true absence of effect.

# **Conclusions**

Currently available evidence is of poor quality, highly heterogeneous, and insufficient to support firm conclusions about the clinical applicability of cefiderocol-based combination therapies. Nevertheless, these findings offer valuable insight into potential directions for future research. Systematic *in vitro* evaluation of cefiderocol-based combinations against well-characterised CR-GNB, using validated and standardised synergy testing methods, is warranted. Particular emphasis should be placed on combinations with BLIs, which are increasingly supported by emerging preclinical data. At the same time, continued investigation of agents such as tigecycline, carbapenems, fosfomycin, colistin and selected non-antibiotic adjuvants remains essential to fully explore their synergistic potential.

Well-structured clinical trials and observational studies with appropriate sample size are needed to define the role of cefiderocol-based combinations, with systematic assessment of clinical outcomes and microbiological endpoints, including resistance emergence. Given the promising in vitro activity and the paucity of clinical trials or high-quality observational studies assessing cefiderocol–BLI combinations, in vivo and clinical evaluation is needed to better define their therapeutic role.

### **Funding**

This work was part of the CLEARER project (Current cLinical scEnARios for the use of cefidErocol in multidrug-Resistant infections: a case study-based approach) supported by the Global Antibiotic Research and Development Partnership (GARDP).

### **Transparency declarations**

No conflicts of interest to declare

### Refrences

::: {#refs}
:::
